### PR TITLE
Adds the gov-wide CX hiring JOA.

### PR DESCRIPTION
**Pull request by humancompanion**
This adds the gov-wide Customer Experience job announcement that USDS plans to co-deploy with OPM next month. The template deviates from the previous USDS pilot in the following ways:

* Required Documents has an additional paragraph about design portfolios, required for this action, in the All applicants drawer.
* Where you will work removes a link to OPM benefits given that OPM won't be the only agency these new employees may work for (it could be one of 25 agencies).
* How you will be evaluated has additional content under the sub-header "Get answers to questions about this process and position"

For now I'd just like to get this approved (I can merge it once approved) so we can share it with Ro in Policy and others who need to review this draft.

### CODE REVIEW

**Comment by Piglady64** [comment]
@humancompanion Who does this need to go to for approval. I want to make sure someone looks at it and it doesn't get lost.

**Comment by Piglady64** [comment]
@humancompanion Never mind I see it went to Sam, Wayne and Michelle.

**Comment by humancompanion** [comment]
@Piglady64 - Yeah, that's who would have looked at it in the past. But if there is a better audience just say so. Michelle is aware of it (we spoke week before last) but I wasn't sure she shared that information. I just wanted to give those folks a heads up that I was creating this new announcement. It's not finalized yet so no real action is required, just approval to merge and deploy it to the design system so other parts of OPM can review. 

The goal is to deploy this in January with an open date of 2/3/2020 so that we and the agencies involved can recruit for it in January.

**Comment by mgearley** [comment]
Can you add Dan to the review, since he is currently the product owner?

**Comment by danthibodeau** [comment]
There's nothing really for me to review here as far as the changes or code since I have no idea how to view it, but @sabushanab @wakaye @ddescombes @Marchalk I'm assuming we'd need a ticket for this. I'm not sure of any of the requirements for timeframe, and I know we're short on developers this sprint. Let me and the BAs know what you need from us.

**Comment by humancompanion** [comment]
@danthibodeau - I really just wanted to make you aware that I was updating the design system with this draft. I don't need anything at this moment. Once Policy gives me feedback on this version and it's ready to go then I'll let you all know that it is ready. 

I'll send an email to you and Michelle with the requirements and timeframe request to support this gov-wide hiring action.

**Comment by danthibodeau** [comment]
Great, thanks Matt! I was thinking you needed this posted immediately, so that makes me much less nervous! :)

**Pull request merged**
